version: 1.0.{build}
image: Visual Studio 2019
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore s3i.sln
build:
  project: s3i.sln
  verbosity: normal
test:
  categories:
    except:
    - Study
    - AWS
deploy:
- provider: GitHub
  auth_token:
    secure: 0GagvW3n7npL5iRUius31zgyPNAhlXbSxymyQIXlKNQHjtFpZEZH3151VANvLQAH
  artifact: /.*\.msi.msi
